"""Offline deterministic Counterseal security-engine building blocks.

The engine package has no Kubernetes client, network, subprocess, model, or
mutation capability.  Its outputs are bounded observations and candidate
artifacts for later verification; an eligible compiler result is never an
approval or an application instruction.
"""

from .audit import (
    AuditEventGroup,
    AuditEventReference,
    AuditNormalizationError,
    AuditNormalizationResult,
    AuditReasonCode,
    ContractAuditResult,
    ContractFindingDisposition,
    NormalizedAuditEvent,
    WorkloadContractFinding,
    detect_contract_violations,
    detect_workload_contract_violations,
    normalize_audit_event,
    normalize_audit_events,
    normalize_audit_records,
)
from .compiler import (
    CandidateCompiler,
    CandidateStatus,
    CompiledCandidate,
    compile_candidate,
)
from .offline_demo import (
    OfflineCandidateSummary,
    OfflineMatrixResult,
    build_demo_role_snapshot,
    run_candidate_matrix,
)
from .policy import (
    CompileRequest,
    PolicyDecision,
    PolicyGate,
    PolicyResult,
    ReasonCode,
    RoleRuleObservation,
    RoleSnapshot,
)
from .rbac import (
    AlternativePathFinding,
    AnalysisResult,
    AnalysisStatus,
    ApiSuccessFact,
    BindingReferenceFact,
    BusinessInvariantFact,
    ClaimContext,
    ClaimVerification,
    ClaimVerifier,
    ClusterRoleBindingRecord,
    ClusterRoleRecord,
    Completeness,
    EffectivePermission,
    EvidenceRef,
    ForbiddenProbeFact,
    MatchingGrant,
    PermissionRequest,
    RbacAnalyzer,
    RbacRuleRecord,
    RbacSnapshotRecord,
    RoleBindingRecord,
    RoleRecord,
    RoleRuleFact,
    ServiceAccountRef,
    SnapshotObjectRecord,
    SnapshotScopeFact,
    SourceObjectFact,
    SubjectRecord,
    analyze_rbac,
    verify_claim,
)
from .rbac import (
    ReasonCode as RbacReasonCode,
)

__all__ = [
    "AnalysisResult",
    "AnalysisStatus",
    "AlternativePathFinding",
    "ApiSuccessFact",
    "AuditEventGroup",
    "AuditEventReference",
    "AuditNormalizationError",
    "AuditNormalizationResult",
    "AuditReasonCode",
    "CandidateCompiler",
    "CandidateStatus",
    "BindingReferenceFact",
    "BusinessInvariantFact",
    "ClaimContext",
    "ClaimVerification",
    "ClaimVerifier",
    "ClusterRoleBindingRecord",
    "ClusterRoleRecord",
    "Completeness",
    "CompileRequest",
    "CompiledCandidate",
    "ContractAuditResult",
    "ContractFindingDisposition",
    "EffectivePermission",
    "EvidenceRef",
    "ForbiddenProbeFact",
    "MatchingGrant",
    "NormalizedAuditEvent",
    "OfflineCandidateSummary",
    "OfflineMatrixResult",
    "PermissionRequest",
    "PolicyDecision",
    "PolicyGate",
    "PolicyResult",
    "RbacAnalyzer",
    "RbacReasonCode",
    "RbacRuleRecord",
    "RbacSnapshotRecord",
    "ReasonCode",
    "RoleRuleObservation",
    "RoleBindingRecord",
    "RoleRecord",
    "RoleRuleFact",
    "RoleSnapshot",
    "ServiceAccountRef",
    "SnapshotObjectRecord",
    "SnapshotScopeFact",
    "SourceObjectFact",
    "SubjectRecord",
    "WorkloadContractFinding",
    "analyze_rbac",
    "build_demo_role_snapshot",
    "compile_candidate",
    "detect_contract_violations",
    "detect_workload_contract_violations",
    "normalize_audit_event",
    "normalize_audit_events",
    "normalize_audit_records",
    "run_candidate_matrix",
    "verify_claim",
]
